name: conever
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  kakao_flutter_sdk: ^1.5.0
  flutter_secure_storage: ^9.0.0
  kakao_flutter_sdk_user: ^1.4.3
  expandable: ^5.0.1
  table_calendar: ^3.2.0
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_dotenv: ^5.1.0
  web_socket_channel: ^3.0.2
  dio: ^5.8.0+1
  intl: ^0.20.2
  dropdown_search: ^5.0.6
  image_gallery_saver: ^2.0.3
  flutter_svg: ^2.2.0
  logger: ^2.6.1
  flutter_naver_map: ^1.4.1+1
  skeletonizer: ^2.1.0+1
  visibility_detector: ^0.4.0+2

  image_picker: ^1.0.4
  image: ^4.0.17
  path_provider: ^2.1.2
  path: ^1.8.3
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0
  smooth_page_indicator: ^1.2.1

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icons/icon.png'
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/icon.png
  android: true
  ios: true
  web: false

dependency_overrides:
  image_gallery_saver:
    path: lib_external/image_gallery_saver

dev_dependencies:
  flutter_native_splash: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env

    - assets/buttons/kakao_login_button.png

    - assets/icons/airport.svg
    - assets/icons/ask_add_page_icon.png
    - assets/icons/delete_tour_page_icon.png
    - assets/icons/final_add_page_icon.png
    - assets/icons/icon.png
    - assets/icons/image_icon.png
    - assets/icons/logo_text.svg
    - assets/icons/logo_white.png
    - assets/icons/map_icon.png
    - assets/icons/missing_image_icon.png
    - assets/icons/plan_card_icon.png
    - assets/icons/plan_page_1_icon.png
    - assets/icons/pose1_icon.png
    - assets/icons/pose2_icon.png
    - assets/icons/pose3_icon.png

    - assets/images/loading2_1.png
    - assets/images/loading2_2.png
    - assets/images/loading2_3.png
    - assets/images/seoul_image.jpg