Map<String, dynamic> getDummyTourList() {
  return {
    "id": 1,
    "tour_name": "태근이의 여행",
    "tour_date": "2025-07-07",
    "user": [
      {
        "sub": 3928446869,
        "username": "TestUser",
        "profile_image_url": "https://example.org",
      },
      {
        "sub": 1122334455,
        "username": "Alice",
        "profile_image_url": "https://example.org/alice.png",
      },
      {
        "sub": 9988776655,
        "username": "Bob",
        "profile_image_url": "https://example.org/bob.png",
      },
    ],
    "places": [
      {
        "tdp_id": 1,
        "place": {
          "id": 8,
          "name": "명원박물관",
          "mapX": 126.9999927956,
          "mapY": 37.6111883307,
          "road_address": "테스트지롱",
          "address": "",
          "contentid": "12",
          "imageUrl": "",
        },
      },
      {
        "tdp_id": 2,
        "place": {
          "id": 9,
          "name": "아산 공세리성당",
          "mapX": 126.9134070332,
          "mapY": 36.8833377411,
          "road_address": "충청남도 아산시 인주면 공세리성당길 10",
          "address": "충청남도 아산시 인주면 공세리성당길 10",
          "contentid": "14",
          "imageUrl": "",
        },
      },
      {
        "tdp_id": 3,
        "place": {
          "id": 10,
          "name": "성북구립미술관",
          "mapX": 126.9949020554,
          "mapY": 37.594890134,
          "road_address": "서울특별시 성북구 성북로 134 (성북동)",
          "address": "서울특별시 성북구 성북로 134",
          "contentid": "14",
          "imageUrl": "",
        },
      },
      {
        "tdp_id": 4,
        "place": {
          "id": 11,
          "name": "경복궁",
          "mapX": 126.9769,
          "mapY": 37.5796,
          "road_address": "서울특별시 종로구 사직로 161",
          "address": "서울특별시 종로구 사직로 161",
          "contentid": "12",
          "imageUrl": "",
        },
      },
      {
        "tdp_id": 5,
        "place": {
          "id": 12,
          "name": "남산서울타워",
          "mapX": 126.9882,
          "mapY": 37.5512,
          "road_address": "서울특별시 용산구 남산공원길 105",
          "address": "서울특별시 용산구 남산공원길 105",
          "contentid": "12",
          "imageUrl": "",
        },
      },
      {
        "tdp_id": 6,
        "place": {
          "id": 13,
          "name": "롯데월드",
          "mapX": 127.0980,
          "mapY": 37.5110,
          "road_address": "서울특별시 송파구 올림픽로 240",
          "address": "서울특별시 송파구 올림픽로 240",
          "contentid": "14",
          "imageUrl": "",
        },
      },
      {
        "tdp_id": 7,
        "place": {
          "id": 14,
          "name": "해운대해수욕장",
          "mapX": 129.1587,
          "mapY": 35.1587,
          "road_address": "부산광역시 해운대구 우동",
          "address": "부산광역시 해운대구 우동",
          "contentid": "12",
          "imageUrl": "",
        },
      },
      {
        "tdp_id": 8,
        "place": {
          "id": 15,
          "name": "성산일출봉",
          "mapX": 126.9410,
          "mapY": 33.4580,
          "road_address": "제주특별자치도 서귀포시 성산읍 성산리 1",
          "address": "제주특별자치도 서귀포시 성산읍 성산리 1",
          "contentid": "12",
          "imageUrl": "",
        },
      },
    ],
  };
}
